# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcspt_app.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TcsptWindow(object):
    def setupUi(self, TcsptWindow):
        TcsptWindow.setObjectName(_fromUtf8("TcsptWindow"))
        TcsptWindow.resize(584, 514)
        self.centralwidget = QtGui.QWidget(TcsptWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ingest_btn = QtGui.QPushButton(self.centralwidget)
        self.ingest_btn.setObjectName(_fromUtf8("ingest_btn"))
        self.horizontalLayout_4.addWidget(self.ingest_btn)
        self.ingest_lbl = QtGui.QLabel(self.centralwidget)
        self.ingest_lbl.setText(_fromUtf8(""))
        self.ingest_lbl.setObjectName(_fromUtf8("ingest_lbl"))
        self.horizontalLayout_4.addWidget(self.ingest_lbl)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.source_btn = QtGui.QPushButton(self.centralwidget)
        self.source_btn.setObjectName(_fromUtf8("source_btn"))
        self.horizontalLayout.addWidget(self.source_btn)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.file_name_lbl = QtGui.QLabel(self.centralwidget)
        self.file_name_lbl.setText(_fromUtf8(""))
        self.file_name_lbl.setObjectName(_fromUtf8("file_name_lbl"))
        self.horizontalLayout_2.addWidget(self.file_name_lbl)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.file_path_lbl = QtGui.QLabel(self.centralwidget)
        self.file_path_lbl.setText(_fromUtf8(""))
        self.file_path_lbl.setObjectName(_fromUtf8("file_path_lbl"))
        self.horizontalLayout_3.addWidget(self.file_path_lbl)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.file_size_lbl = QtGui.QLabel(self.centralwidget)
        self.file_size_lbl.setText(_fromUtf8(""))
        self.file_size_lbl.setObjectName(_fromUtf8("file_size_lbl"))
        self.horizontalLayout_5.addWidget(self.file_size_lbl)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checksum_btn = QtGui.QPushButton(self.centralwidget)
        self.checksum_btn.setObjectName(_fromUtf8("checksum_btn"))
        self.horizontalLayout_6.addWidget(self.checksum_btn)
        self.stop_btn = QtGui.QPushButton(self.centralwidget)
        self.stop_btn.setEnabled(False)
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.horizontalLayout_6.addWidget(self.stop_btn)
        self.checksum_progress = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checksum_progress.sizePolicy().hasHeightForWidth())
        self.checksum_progress.setSizePolicy(sizePolicy)
        self.checksum_progress.setMaximum(1)
        self.checksum_progress.setProperty("value", 0)
        self.checksum_progress.setTextVisible(False)
        self.checksum_progress.setInvertedAppearance(False)
        self.checksum_progress.setObjectName(_fromUtf8("checksum_progress"))
        self.horizontalLayout_6.addWidget(self.checksum_progress)
        self.checksum_lbl = QtGui.QLabel(self.centralwidget)
        self.checksum_lbl.setText(_fromUtf8(""))
        self.checksum_lbl.setObjectName(_fromUtf8("checksum_lbl"))
        self.horizontalLayout_6.addWidget(self.checksum_lbl)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.export_btn = QtGui.QPushButton(self.centralwidget)
        self.export_btn.setObjectName(_fromUtf8("export_btn"))
        self.horizontalLayout_7.addWidget(self.export_btn)
        self.export_lbl = QtGui.QLabel(self.centralwidget)
        self.export_lbl.setText(_fromUtf8(""))
        self.export_lbl.setObjectName(_fromUtf8("export_lbl"))
        self.horizontalLayout_7.addWidget(self.export_lbl)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        TcsptWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TcsptWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        TcsptWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TcsptWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TcsptWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TcsptWindow)
        QtCore.QMetaObject.connectSlotsByName(TcsptWindow)

    def retranslateUi(self, TcsptWindow):
        TcsptWindow.setWindowTitle(_translate("TcsptWindow", "TcsPT App", None))
        self.ingest_btn.setText(_translate("TcsptWindow", "Ingest Xml", None))
        self.source_btn.setText(_translate("TcsptWindow", "Select File", None))
        self.label.setText(_translate("TcsptWindow", "File Name:", None))
        self.label_2.setText(_translate("TcsptWindow", "File Path:", None))
        self.label_3.setText(_translate("TcsptWindow", "File Size:", None))
        self.checksum_btn.setText(_translate("TcsptWindow", "Calculate Checksum", None))
        self.stop_btn.setText(_translate("TcsptWindow", "Stop", None))
        self.export_btn.setText(_translate("TcsptWindow", "Update Xml", None))

